server:
  port: 8888

spring:
  application:
    name: cloudconfigserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kodebinder/cloudconfigserverconfiguration
          clone-on-start: true