server:
  port: 8765

spring:
  application:
    name: cloudgateway
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://userservice
          predicates:
            - Path=/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userservice
                fallbackuri: forward:/userServiceFallBack
        - id: urlservice
          uri: lb://urlservice
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: urlservice
                fallbackuri: forward:/urlServiceFallBack


hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream