server:
  port: 9021
  error:
    include-message: always
    include-stacktrace: always
    whitelabel:
      enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1-server.com:9001/eureka, http://eureka-2-server.com:9002/eureka, http://eureka-3-server.com:9003/eureka
spring:
  application:
    name: urlservice
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
  zipkin:
    base-url: http://127.0.0.1:9411/
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    url: 'jdbc:mysql://localhost:3306/url'
#    password: Welcome@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: url
      host: localhost
      port: 27017
springdoc:
  api-docs:
    enabled: true
    path: /url-docs