server:
  port: 9031
  error:
    include-message: always
    include-stacktrace: always
    whitelabel:
      enabled: false
spring:
  application:
    name: userservice
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  kafka:
    bootstrap-servers: localhost:9092
  zipkin:
    base-url: http://127.0.0.1:9411/
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #    username: root
  #    url: 'jdbc:mysql://localhost:3306/user'
  #    password: Welcome@123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: 'true'
    hibernate:
      ddl-auto: update
  data:
    mongodb:
      database: user
      host: localhost
      port: 27017
springdoc:
  api-docs:
    enabled: true
    path: /user-docs